version: '3'

services:
  api:
    container_name: "permission-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    env_file:
      - .env

  db:
    container_name: postgres_db
    image: postgres:12
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true