version: '3'
services:
  api:
    container_name: "permission-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
        - db
#    healthcheck:
#      test: ["CMD", "curl", "-f", "http://localhost:${PORT}/api/health/check"]
#      interval: 30s
#      timeout: 10s
#      retries: 3

  db:
    container_name: postgres_db
    image: postgres:12
    env_file:
      - .env
    ports:
        - ${DB_PORT}:${DB_PORT}
    environment:
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:

networks:
  wii-network:
    external: true