spring:
  application:
    name: permission-service
  datasource:
    url: jdbc:postgresql://${PERMISSION_DB_HOST}:${PERMISSION_DB_PORT}/${PERMISSION_POSTGRES_DB}
    driver-class-name: org.postgresql.Driver
    username: ${PERMISSION_POSTGRES_USER}
    password: ${PERMISSION_POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${AUTH_SERVER_URI}
          client-id: ${AUTH_CLIENT_ID}
          client-secret: ${AUTH_CLIENT_SECRET}
auth0:
  audience: ${AUTH0_AUDIENCE}

ui:
  url: ${UI_URL}
server:
  port: ${PERMISSION_PORT}