name: "Continuous Deployment"
on:
  push:
    branches:
      - main
      - dev
jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build project and create JAR
        run: ./gradlew clean build

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: permission-service-jar
          path: build/libs/permission-service-1.0.0.jar

  deploy:
    name: Deploy Project
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: permission-service-jar
          path: build/libs

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image for dev
        if: github.ref == 'refs/heads/dev'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/ing-sistemas/permission-service:dev

      - name: Build and push Docker image for production
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: |
            ghcr.io/ing-sistemas/permission-service:latest

#      - name: Push to GitHub Packages
#        id: docker_build
#        uses: docker/build-push-action@v4
#        with:
#          push: true
#          tags: |
#            ghcr.io/Ing-Sistemas/Permission-Service